import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTrip } from '../context/TripContext'
import { useAuth } from '../context/AuthContext'
import { saveItinerary } from '../api'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import toast from 'react-hot-toast'
import { Save, Download, Share2, Navigation } from 'lucide-react'

export default function SaveExport() {
  const { itinerary, meta, savedId, setSavedId } = useTrip()
  const { user } = useAuth()
  const nav = useNavigate()
  const [saving, setSaving] = useState(false)

  const handleSave = async () => {
    if (!user) return toast.error('Please sign in')
    setSaving(true)
    try {
      const payload = { destination: meta?.destination, days: meta?.days, itinerary }
      const res = await saveItinerary(user.uid, payload)
      setSavedId(res.data.itinerary_id)
      toast.success('Itinerary saved to your profile!')
    } catch (e) {
      toast.error('Save failed: ' + (e.response?.data?.detail || e.message))
    } finally { setSaving(false) }
  }

  const handleExportPDF = () => {
    const doc = new jsPDF()
    doc.setFontSize(18)
    doc.text(`${meta?.destination} Travel Itinerary`, 14, 20)
    doc.setFontSize(11)
    doc.text(`${meta?.days} days • ${meta?.travel_type} • ${meta?.budget} budget`, 14, 30)

    autoTable(doc, {
      startY: 40,
      head: [['Day', 'Time', 'Place', 'Category', 'Duration', 'Entry Fee', 'Tip']],
      body: itinerary.map(s => [
        `Day ${s.day}`, s.time, s.place_name, s.category || '-',
        `${s.duration_hrs}hr`, s.entry_fee !== undefined ? `Rs.${s.entry_fee}` : '-',
        s.tip || '-'
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [37, 99, 235] }
    })

    doc.save(`${meta?.destination}-itinerary.pdf`)
    toast.success('PDF downloaded!')
  }

  const handleWhatsApp = () => {
    const text = `Check out my ${meta?.destination} trip plan!\nGenerated by AI Tourism Planner`
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank')
  }

  return (
    <div className="max-w-xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-white mb-2">💾 Save & Share</h1>
      <p className="text-slate-400 mb-8">Your {meta?.destination} itinerary is ready!</p>

      <div className="space-y-4">
        <button onClick={handleSave} disabled={saving || !!savedId}
          className="w-full flex items-center justify-center gap-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-4 rounded-xl transition disabled:opacity-60"
        >
          <Save size={20} />
          {savedId ? '✅ Saved to Profile' : saving ? 'Saving...' : 'Save to My Profile'}
        </button>

        <button onClick={handleExportPDF}
          className="w-full flex items-center justify-center gap-3 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-4 rounded-xl transition"
        >
          <Download size={20} /> Export as PDF
        </button>

        <button onClick={handleWhatsApp}
          className="w-full flex items-center justify-center gap-3 bg-green-600 hover:bg-green-700 text-white font-semibold py-4 rounded-xl transition"
        >
          <Share2 size={20} /> Share via WhatsApp
        </button>

        <div className="flex gap-4 mt-2">
          <button onClick={() => nav('/itinerary')} className="flex-1 bg-slate-800 border border-slate-700 text-white py-3 rounded-xl text-sm hover:bg-slate-700">
            ← Back to Itinerary
          </button>
          <button onClick={() => nav('/live')}
            className="flex-1 flex items-center justify-center gap-2 bg-green-600 hover:bg-green-700 text-white py-3 rounded-xl text-sm"
          >
            <Navigation size={16} /> Start Live Mode
          </button>
        </div>
      </div>
    </div>
  )
}
